.TH "MERGE" 1 "2015-03-04" "Merge" "Merge Manual"
.SH "NAME"
merge is a tool which merges subgraph isomorphisms in graphs into single
nodes.
.SH "SYNOPSIS"
merge
.I "[option...]"
.I "[argument...]"
.PP
.SH "OPTIONS"
.B "-img"
.RS 4
Generate an image representation of the CFG.
.RE
.PP
.B "-o"
<string>
.RS 4
.RS 4
Output path of the graph.
.RE
.RE
.PP
.B "-q"
.RS 4
.RS 4
Suppress non-error messages.
.RE
.RE
.PP
.B "-start"
<string>
.RS 4
.RS 4
Merge an isomorphism of SUB in GRAPH which starts at the given node.
.RE
.RE
.PP
