.TH "LL2DOT" 1 "2015-03-04" "Ll2dot" "Ll2dot Manual"
.SH "NAME"
ll2dot is a tool which generates control flow graphs from LLVM IR assembly files
(e.g. *.ll -> *.dot). The output is a set of Graphviz DOT files, each
representing the control flow graph of a function using one node per basic
block.

For a source file "foo.ll" containing the functions "bar" and "baz" the
following DOT files will be generated:

   * foo_graphs/bar.dot
   * foo_graphs/baz.dot
.SH "SYNOPSIS"
ll2dot
.I "[option...]"
.I "[argument...]"
.PP
.SH "OPTIONS"
.B "-f"
.RS 4
Force overwrite existing graph directories.
.RE
.PP
.B "-funcs"
<string>
.RS 4
.RS 4
Comma separated list of functions to parse (e.g. "foo,bar").
.RE
.RE
.PP
.B "-img"
.RS 4
.RS 4
Generate an image representation of the CFG.
.RE
.RE
.PP
.B "-q"
.RS 4
.RS 4
Suppress non-error messages.
.RE
.RE
.PP
